import type {
  AiAgent,
  AiRole,
  AiSkill,
  AnalysisLogEvent,
  AnalysisReport,
  CodexAuthStatus,
  Workspace,
} from "@speclens/contracts";

export const mockWorkspace: Workspace = {
  id: "workspace_demo",
  ownerUserId: "user_demo",
  name: "Nordic Platform Team",
  slug: "nordic-platform-team",
  description: "Shared workspace for SaaS trial runs and report review.",
  entitlement: "pro",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const mockLogs: AnalysisLogEvent[] = [
  {
    id: "log_1",
    jobId: "job_demo",
    level: "info",
    scope: "queue",
    message: "Job accepted by hosted runner plane.",
    visibility: "default",
    createdAt: new Date().toISOString(),
  },
  {
    id: "log_2",
    jobId: "job_demo",
    level: "info",
    scope: "source",
    message: "Fetched GitHub source and sealed it into the sandbox bundle.",
    visibility: "default",
    createdAt: new Date().toISOString(),
  },
  {
    id: "log_3",
    jobId: "job_demo",
    level: "info",
    scope: "analysis",
    message: "Generated report.json and pushed artifacts to S3-compatible object storage.",
    visibility: "default",
    createdAt: new Date().toISOString(),
  },
];

export const mockReport: AnalysisReport = {
  id: "report_demo",
  workspaceId: mockWorkspace.id,
  jobId: "job_demo",
  status: "ready",
  roles: [
    { id: "source-topology-scout", title: "Source topology scout", description: "", order: 0, dependsOnRoleIds: [], skills: [] },
    { id: "license-governor", title: "License governor", description: "", order: 1, dependsOnRoleIds: [], skills: [] },
    { id: "navigation-qa-planner", title: "Navigation QA planner", description: "", order: 2, dependsOnRoleIds: [], skills: [] },
    { id: "visual-qa-critic", title: "Visual QA critic", description: "", order: 3, dependsOnRoleIds: [], skills: [] },
    { id: "ux-friction-reviewer", title: "UX friction reviewer", description: "", order: 4, dependsOnRoleIds: [], skills: [] },
    { id: "artifact-auditor", title: "Artifact auditor", description: "", order: 5, dependsOnRoleIds: [], skills: [] },
    { id: "release-gate-scorer", title: "Release gate scorer", description: "", order: 6, dependsOnRoleIds: [], skills: [] },
  ],
  runtimeMode: "browser",
  title: "SpecLens hosted analysis report",
  summary: {
    totalFindings: 3,
    high: 1,
    medium: 1,
    low: 1,
    auditBundleId: "standard",
    categoryCounts: {
      license: 1,
      navigation: 1,
      ux: 1,
    },
    releaseGateDecision: {
      status: "warn",
      reason: "Medium-severity operational and UX gaps remain open.",
      confidence: "medium",
      blockingFindingIds: [],
    },
    remediationPacks: [],
    fixHandoff: null,
    changeset: null,
    latestRemediationJobId: null,
    executionCoverage: {
      attempted: [],
      skipped: [],
    },
    qualityScorecard: null,
    capabilityGaps: [],
    artifactAnalysis: null,
    executionSteps: [],
  },
  findings: [
    {
      id: "finding_1",
      roleId: "license-governor",
      category: "license",
      severity: "medium",
      title: "Billing webhook rotation should be rehearsed before launch",
      message: "The hosted stack verifies signed webhooks, but secret rotation and replay drills should still be exercised in staging.",
      suggestion: "Document and rehearse Stripe and GitHub webhook secret rotation before wider rollout.",
      evidence: ["STRIPE_WEBHOOK_SECRET", "GITHUB_APP_WEBHOOK_SECRET"],
      evidenceRefs: [],
      sourceIds: ["source_demo"],
      paths: [],
      remediationPackIds: [],
    },
    {
      id: "finding_2",
      roleId: "navigation-qa-planner",
      category: "navigation",
      severity: "medium",
      title: "Runner droplet pool is at minimum redundancy",
      message: "Only one runner host is currently allocated for the demo workload.",
      suggestion: "Add at least one additional runner droplet before opening access more broadly.",
      evidence: ["runner:maxConcurrency=1"],
      evidenceRefs: [],
      sourceIds: ["source_demo"],
      paths: [],
      remediationPackIds: [],
    },
    {
      id: "finding_3",
      roleId: "release-gate-scorer",
      category: "ux",
      severity: "low",
      title: "Commercial license CTA is informational only",
      message: "The commercial-license page routes users to contact rather than a CRM-backed request flow.",
      suggestion: "Connect the CTA to a captured lead flow when sales operations are ready.",
      evidence: ["/commercial"],
      evidenceRefs: [],
      sourceIds: ["source_demo"],
      paths: [],
      remediationPackIds: [],
    },
  ],
  sections: [
    {
      id: "section_1",
      roleId: "source-topology-scout",
      title: "Source topology",
      status: "ready",
      summary: "The hosted demo sees a TypeScript monorepo with web, API, runner, and shared packages.",
      data: { manifests: 7 },
    },
    {
      id: "section_2",
      roleId: "navigation-qa-planner",
      title: "Navigation QA plan",
      status: "ready",
      summary: "The demo run completed sandbox browser coverage with protected-route support and crawl evidence.",
      data: { routeCandidates: ["/", "/pricing", "/portal/workspaces"], authenticated: true },
    },
    {
      id: "section_3",
      roleId: "release-gate-scorer",
      title: "Release gate",
      status: "ready",
      summary: "The top issues are the missing billing secret, low runner redundancy, and sales-flow incompleteness.",
      data: { releaseGateDecision: "warn", topFindings: ["finding_1", "finding_2", "finding_3"] },
    },
  ],
  artifacts: [],
  createdAt: new Date().toISOString(),
};

export const mockCodexAuthStatus: CodexAuthStatus = {
  scope: "global",
  status: "unauthenticated",
  authMode: null,
  accountId: null,
  userCode: null,
  verificationUri: null,
  verificationUriComplete: null,
  expiresAt: null,
  intervalSeconds: null,
  lastError: null,
  lastRefresh: null,
  disabled: false,
};

export const mockAiSkills: AiSkill[] = [
  {
    id: "skill-evidence-discipline",
    name: "Evidence discipline",
    description: "Ground findings in concrete repository or runtime evidence.",
    instructions: "Only emit findings that are backed by concrete repo files, runtime output, or browser artifacts.",
    toolCapabilities: ["repo-read", "shell-exec", "package-install", "dev-server", "test-exec"],
    order: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-site-navigation-qa",
    name: "Site navigation QA",
    description: "Translate routes and flows into a browser-visible QA plan.",
    instructions: "Map routes, auth boundaries, journeys, assertion focus, and artifact expectations from router code, tests, and docs.",
    toolCapabilities: ["repo-read", "browser-automation", "artifact-write", "test-exec", "auth-state"],
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-remediation-pack-formatting",
    name: "Remediation pack formatting",
    description: "Group findings into fix-ready remediation packs.",
    instructions: "Group findings by subsystem and dependency order so later fix agents can act on them deterministically.",
    toolCapabilities: ["repo-read", "artifact-write"],
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockAiRoles: AiRole[] = [
  {
    id: "source-topology-scout",
    name: "Source topology scout",
    description: "Classify repo shape, applications, and likely product surfaces.",
    prompt: "Survey the repository shape and emit a structured Source topology section.",
    order: 0,
    consoleVisibility: "quiet",
    executorKind: "hybrid",
    nativeExecutorId: "native-repo-inventory",
    dependsOnRoleIds: [],
    skills: [{ id: "skill-evidence-discipline", name: "Evidence discipline" }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "runtime-scout",
    name: "Runtime scout",
    description: "Discover install, boot, and verification commands for the repo.",
    prompt: "Figure out how to run the repository and report concrete commands, services, ports, and blockers.",
    order: 1,
    consoleVisibility: "normal",
    executorKind: "codex",
    nativeExecutorId: null,
    dependsOnRoleIds: [],
    skills: mockAiSkills.map(skill => ({ id: skill.id, name: skill.name })),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "auth-cartographer",
    name: "Auth cartographer",
    description: "Map frontend and API authentication without inventing secrets.",
    prompt: "Find login routes, callback paths, auth providers, secret refs, and protected routes.",
    order: 2,
    consoleVisibility: "normal",
    executorKind: "codex",
    nativeExecutorId: null,
    dependsOnRoleIds: ["runtime-scout"],
    skills: mockAiSkills.map(skill => ({ id: skill.id, name: skill.name })),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "navigation-qa-planner",
    name: "Navigation QA planner",
    description: "Map browser-visible routes, journeys, and assertion targets before execution.",
    prompt: "Identify navigation targets, auth boundaries, core journeys, assertions, and artifact expectations for site QA.",
    order: 3,
    consoleVisibility: "normal",
    executorKind: "codex",
    nativeExecutorId: null,
    dependsOnRoleIds: ["runtime-scout", "auth-cartographer"],
    skills: mockAiSkills.map(skill => ({ id: skill.id, name: skill.name })),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "playwright-operator",
    name: "Playwright operator",
    description: "Turn runtime and auth findings into a Playwright execution plan.",
    prompt: "Inspect Playwright coverage and derive the setup, auth, and execution path.",
    order: 4,
    consoleVisibility: "normal",
    executorKind: "codex",
    nativeExecutorId: null,
    dependsOnRoleIds: ["runtime-scout", "auth-cartographer", "navigation-qa-planner"],
    skills: mockAiSkills.map(skill => ({ id: skill.id, name: skill.name })),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "standardized-json-output",
    name: "Standardized JSON output",
    description: "Emit one canonical machine-readable handoff.",
    prompt: "Produce a normalized JSON handoff for downstream operators.",
    order: 5,
    consoleVisibility: "normal",
    executorKind: "codex",
    nativeExecutorId: null,
    dependsOnRoleIds: ["runtime-scout", "auth-cartographer", "navigation-qa-planner", "playwright-operator"],
    skills: mockAiSkills.map(skill => ({ id: skill.id, name: skill.name })),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockAiAgents: AiAgent[] = [
  {
    id: "agent-universal-smoke",
    name: "Universal audit smoke agent",
    description: "Fast intake bundle for repository topology, runtime confidence, and highest-risk blockers.",
    order: 0,
    roles: [{ id: "source-topology-scout", name: "Source topology scout", order: 0 }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "agent-universal-standard",
    name: "Universal audit standard agent",
    description: "Broad repository, runtime, browser, UX, and remediation audit bundle.",
    order: 1,
    roles: mockAiRoles
      .filter(role => role.id !== "source-topology-scout")
      .map(role => ({ id: role.id, name: role.name, order: role.order })),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
