import path from "node:path";
import type { AnalysisReport } from "@speclens/contracts";
import { nowIso, writeJsonFile, writeTextFile } from "./utils";
import { createWorkspace, getRunEnvelope, type WorkspaceOptions } from "./workspace";

export interface ExportPatchSelection {
  findingIds?: string[];
}

export interface ExportPatchOperation {
  findingId: string;
  severity: AnalysisReport["findings"][number]["severity"];
  title: string;
  suggestion: string;
}

export interface ExportPatchResult {
  exportId: string;
  exportDir: string;
  bundlePath: string;
  readmePath: string;
  operations: ExportPatchOperation[];
}

export type ExportPatchOptions = WorkspaceOptions;

function selectFindings(report: AnalysisReport, selection: ExportPatchSelection): AnalysisReport["findings"] {
  if (!selection.findingIds || selection.findingIds.length === 0) {
    return report.findings;
  }

  const requested = new Set(selection.findingIds);
  return report.findings.filter(finding => requested.has(finding.id));
}

export function exportPatchBundle(
  runId: string,
  selection: ExportPatchSelection = {},
  options: ExportPatchOptions = {},
): ExportPatchResult {
  const workspace = createWorkspace(options);
  const run = getRunEnvelope(runId, {
    rootDir: workspace.rootDir,
    name: workspace.name,
    workspaceRoot: workspace.workspaceRoot,
  });

  if (!run.report) {
    throw new Error(`Run ${runId} does not have an attached report to export.`);
  }

  const findings = selectFindings(run.report, selection);
  if (findings.length === 0) {
    throw new Error(`Run ${runId} does not contain any findings for the requested selection.`);
  }

  const exportId = `${runId}-${nowIso().slice(0, 19).replace(/[:T]/g, "-")}`;
  const exportDir = path.join(workspace.exportsDir, "patches", exportId);
  const operations: ExportPatchOperation[] = findings.map(finding => ({
    findingId: finding.id,
    severity: finding.severity,
    title: finding.title,
    suggestion: finding.suggestion,
  }));

  const bundlePath = path.join(exportDir, "patch-bundle.json");
  const readmePath = path.join(exportDir, "README.md");

  writeJsonFile(bundlePath, {
    exportId,
    runId,
    workspace: workspace.name,
    createdAt: nowIso(),
    reportId: run.report.id,
    operations,
  });
  writeTextFile(
    readmePath,
    [
      `# Patch Export ${exportId}`,
      "",
      `Run: \`${runId}\``,
      `Workspace: \`${workspace.name}\``,
      "",
      "This export is a reviewable change manifest generated by SpecLens.",
      "It does not mutate the target repository.",
      "",
      "## Selected findings",
      "",
      ...operations.map(operation =>
        `- \`${operation.findingId}\` (${operation.severity}): ${operation.title} -> ${operation.suggestion}`,
      ),
    ].join("\n"),
  );

  return {
    exportId,
    exportDir,
    bundlePath,
    readmePath,
    operations,
  };
}
