ALTER TABLE "AnalysisJob"
  ALTER COLUMN "engine" DROP NOT NULL,
  ALTER COLUMN "engine" DROP DEFAULT,
  ALTER COLUMN "preset" DROP NOT NULL,
  ALTER COLUMN "preset" DROP DEFAULT;

ALTER TABLE "AnalysisReport"
  ALTER COLUMN "preset" DROP NOT NULL,
  ALTER COLUMN "preset" DROP DEFAULT;
